on: 
  push:
    branches:
      - master

jobs:
  release-on-push:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
